name: flexconv
channels:
  - pytorch
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex>=0.1
  - anyio>=2.1.0
  - argh>=0.26.2
  - argon2-cffi>=20.1.0
  - async_generator>=1.10
  - attrs>=20.3.0
  - babel>=2.9.0
  - backcall>=0.2.0
  - backports>=1.0
  - backports.functools_lru_cache>=1.6.1
  - blas>=1.0
  - bleach>=3.3.0
  - brotlipy>=0.7.0
  - ca-certificates>=2020.10.14
  - certifi>=2020.6.20
  - cffi>=1.14.4
  - chardet>=4.0.0
  - click>=7.1.2
  - configparser>=5.0.1
  - cryptography>=2.9.2
  - cudatoolkit>=10.1.243
  - cycler>=0.10.0
  - decorator>=4.4.2
  - defusedxml>=0.6.0
  - docker-pycreds>=0.4.0
  - entrypoints>=0.3
  - freetype>=2.10.4
  - gitdb>=4.0.5
  - gitpython>=3.1.12
  - gql>=0.1.0
  - graphql-core>=3.1.3
  - icu>=67.1
  - idna>=2.10
  - importlib-metadata>=3.4.0
  - importlib_metadata>=3.4.0
  - intel-openmp>=2020.2
  - ipykernel>=5.4.3
  - ipython>=7.20.0
  - ipython_genutils>=0.2.0
  - jedi>=0.18.0
  - jinja2>=2.11.3
  - joblib>=0.17.0
  - jpeg>=9b
  - json5>=0.9.5
  - jsonschema>=3.2.0
  - jupyter_client>=6.1.11
  - jupyter_core>=4.7.1
  - jupyter_server>=1.3.0
  - jupyterlab>=3.0.7
  - jupyterlab_pygments>=0.1.2
  - jupyterlab_server>=2.2.0
  - kiwisolver>=1.3.1
  - lcms2>=2.11
  - ld_impl_linux-64>=2.33.1
  - libedit>=3.1.20191231
  - libffi>=3.3
  - libgcc-ng>=9.1.0
  - libgfortran-ng>=7.3.0
  - libpng>=1.6.37
  - libprotobuf>=3.13.0.1
  - libsodium>=1.0.18
  - libstdcxx-ng>=9.1.0
  - libtiff>=4.1.0
  - libuv>=1.40.0
  - lz4-c>=1.9.3
  - markupsafe>=1.1.1
  - matplotlib>=3.2.2
  - matplotlib-base>=3.2.2
  - mistune>=0.8.4
  - mkl>=2020.2
  - mkl-service>=2.3.0
  - mkl_fft>=1.2.0
  - mkl_random>=1.1.1
  - nbclassic>=0.2.6
  - nbclient>=0.5.1
  - nbconvert>=6.0.7
  - nbformat>=5.1.2
  - ncurses>=6.2
  - nest-asyncio>=1.4.3
  - ninja>=1.10.2
  - notebook>=6.2.0
  - numpy>=1.19.2
  - numpy-base>=1.19.2
  - nvidia-ml>=7.352.0
  - olefile>=0.46
  - openssl>=1.1.1h
  - packaging>=20.9
  - pandoc>=2.11.4
  - pandocfilters>=1.4.2
  - parso>=0.8.1
  - pathtools>=0.1.2
  - pexpect>=4.8.0
  - pickleshare>=0.7.5
  - pillow>=8.1.0
  - pip>=20.3.3
  - prometheus_client>=0.9.0
  - promise>=2.3
  - prompt-toolkit>=3.0.14
  - protobuf>=3.13.0.1
  - psutil>=5.7.3
  - ptyprocess>=0.7.0
  - pycparser>=2.20
  - pygments>=2.7.4
  - pyopenssl>=19.1.0
  - pyparsing>=2.4.7
  - pyrsistent>=0.17.3
  - pysocks>=1.7.1
  - python>=3.7.9
  - python-dateutil>=2.8.1
  - python_abi>=3.7
  - pytorch>=1.7.1
  - pytz>=2021.1
  - pyyaml>=5.3.1
  - pyzmq>=20.0.0
  - readline>=8.1
  - requests>=2.25.1
  - scikit-learn>=0.23.2
  - scipy>=1.6.0
  - send2trash>=1.5.0
  - sentry-sdk>=0.19.5
  - setuptools>=52.0.0
  - shortuuid>=1.0.1
  - six>=1.15.0
  - smmap>=3.0.5
  - sniffio>=1.2.0
  - sqlite>=3.33.0
  - subprocess32>=3.5.4
  - terminado>=0.9.2
  - testpath>=0.4.4
  - threadpoolctl>=2.1.0
  - tk>=8.6.10
  - torchaudio>=0.7.2
  - torchmetrics>=0.3
  - torchvision>=0.8.2
  - tornado>=6.1
  - traitlets>=5.0.5
  - tqdm
  - typing_extensions>=3.7.4.3
  - urllib3>=1.26.3
  - wandb>=0.10.18
  - watchdog>=0.10.4
  - wcwidth>=0.2.5
  - webencodings>=0.5.1
  - wheel>=0.36.2
  - xz>=5.2.5
  - yaml>=0.2.5
  - zeromq>=4.3.3
  - zipp>=3.4.0
  - zlib>=1.2.11
  - zstd>=1.4.5
  - pip:
    - absl-py>=0.11.0
    - contextlib2>=0.6.0.post1
    - llvmlite>=0.35.0
    - ml-collections>=0.1.0
    - numba>=0.52.0
    - pandas>=1.2.2
    - patsy>=0.5.1
    - sktime>=0.5.3
    - statsmodels>=0.12.2
    - torchinfo>=0.0.8
